module.exports = {
    GET_TOTAL_FARMERS:'SELECT COUNT(*) AS total_farmers FROM farmers',
    GET_TOTAL_FARMERS_BY_SEX:'SELECT COUNT(*) FROM farmers WHERE fk_sex=$1',
    GET_TOTAL_WIDOWED_FARMERS:'SELECT COUNT(*) FROM farmers WHERE fk_civil_status=4',
    GET_TOTAL_AGE_CLASS_1_FARMERS:'SELECT COUNT(*) FROM farmers WHERE age < 20',
    GET_TOTAL_AGE_CLASS_2_FARMERS:'SELECT COUNT(*) FROM farmers WHERE age BETWEEN 20 AND 29',
    GET_TOTAL_AGE_CLASS_3_FARMERS:'SELECT COUNT(*) FROM farmers WHERE age BETWEEN 30 AND 39',
    GET_TOTAL_AGE_CLASS_4_FARMERS:'SELECT COUNT(*) FROM farmers WHERE age BETWEEN 40 AND 49',
    GET_TOTAL_AGE_CLASS_5_FARMERS:'SELECT COUNT(*) FROM farmers WHERE age BETWEEN 50 AND 59',
    GET_TOTAL_AGE_CLASS_6_FARMERS:'SELECT COUNT(*) FROM farmers WHERE age >= 60',
}