export const DISEASES_LIST_REQUEST='DISEASES_LIST_REQUEST'
export const DISEASES_LIST_SUCCESS='DISEASES_LIST_SUCCESS'
export const DISEASES_LIST_FAIL='DISEASES_LIST_FAIL'

export const DISEASES_ADD_REQUEST='DISEASES_ADD_REQUEST'
export const DISEASES_ADD_SUCCESS='DISEASES_ADD_SUCCESS'
export const DISEASES_ADD_FAIL='DISEASES_ADD_FAIL'

