export const FETCH_ALL_FARMERS='FETCH_ALL_FARMERS'

export const FARMER_LIST_REQUEST='FARMER_LIST_REQUEST'
export const FARMER_LIST_SUCCESS='FARMER_LIST_SUCCESS'
export const FARMER_LIST_FAIL='FARMER_LIST_FAIL'

export const FARMER_DETAILS_REQUEST='FARMER_DETAILS_REQUEST'
export const FARMER_DETAILS_SUCCESS='FARMER_DETAILS_SUCCESS'
export const FARMER_DETAILS_FAIL='FARMER_DETAILS_FAIL'

export const FARMER_ADD_REQUEST='FARMER_ADD_REQUEST'
export const FARMER_ADD_SUCCESS='FARMER_ADD_SUCCESS'
export const FARMER_ADD_FAIL='FARMER_ADD_FAIL'

export const FARMER_UPDATE_REQUEST='FARMER_UPDATE_REQUEST'
export const FARMER_UPDATE_SUCCESS='FARMER_UPDATE_SUCCESS'
export const FARMER_UPDATE_FAIL='FARMER_ADD_FAIL'