export const FARMS_LIST_REQUEST='FARMS_LIST_REQUEST'
export const FARMS_LIST_SUCCESS='FARMS_LIST_SUCCESS'
export const FARMS_LIST_FAIL='FARMS_LIST_FAIL'

export const FARMER_FARMS_REQUEST='FARMER_FARMS_REQUEST'
export const FARMER_FARMS_SUCCESS='FARMER_FARMS_SUCCESS'
export const FARMER_FARMS_FAIL='FARMS_FARMS_FAIL'

export const FARM_DETAILS_REQUEST='FARM_DETAILS_REQUEST'
export const FARM_DETAILS_SUCCESS='FARM_DETAILS_SUCCESS'
export const FARM_DETAILS_FAIL='FARM_DETAILS_FAIL'

export const FARM_PESTS_REQUEST='FARM_PESTS_REQUEST'
export const FARM_PESTS_SUCCESS='FARM_PESTS_SUCCESS'
export const FARM_PESTS_FAIL='FARM_PESTS_FAIL'

export const FARM_DISEASES_REQUEST='FARM_DISEASES_REQUEST'
export const FARM_DISEASES_SUCCESS='FARM_DISEASES_SUCCESS'
export const FARM_DISEASES_FAIL='FARM_DISEASES_FAIL'

export const FARM_PRACTICES_REQUEST='FARM_PRACTICES_REQUEST'
export const FARM_PRACTICES_SUCCESS='FARM_PRACTICES_SUCCESS'
export const FARM_PRACTICES_FAIL='FARM_PRACTICES_FAIL'

export const ADD_FARM_DETAILS_REQUEST='ADD_FARM_DETAILS_REQUEST'
export const ADD_FARM_DETAILS_SUCCESS='ADD_FARM_DETAILS_SUCCESS'
export const ADD_FARM_DETAILS_FAIL='ADD_FARM_DETAILS_FAIL'

export const UPDATE_FARM_PEST_REQUEST='UPDATE_FARM_PEST_REQUEST'
export const UPDATE_FARM_PEST_SUCCESS='UPDATE_FARM_PEST_SUCCESS'
export const UPDATE_FARM_PEST_FAIL='UPDATE_FARM_PEST_FAIL'

export const UPDATE_FARM_DISEASE_REQUEST='UPDATE_FARM_DISEASE_REQUEST'
export const UPDATE_FARM_DISEASE_SUCCESS='UPDATE_FARM_DISEASE_SUCCESS'
export const UPDATE_FARM_DISEASE_FAIL='UPDATE_FARM_DISEASE_FAIL'

export const UPDATE_FARM_PRACTICES_REQUEST='UPDATE_FARM_PRACTICES_REQUEST'
export const UPDATE_FARM_PRACTICES_SUCCESS='UPDATE_FARM_PRACTICES_SUCCESS'
export const UPDATE_FARM_PRACTICES_FAIL='UPDATE_FARM_PRACTICES_FAIL'

export const UPDATE_FARM_DETAILS_REQUEST='UPDATE_FARM_DETAILS_REQUEST'
export const UPDATE_FARM_DETAILS_SUCCESS='UPDATE_FARM_DETAILS_SUCCESS'
export const UPDATE_FARM_DETAILS_FAIL='UPDATE_FARM_DETAILS_FAIL'
