export const FETCH_ALL_FARMERS='FETCH_ALL_FARMERS'
export const ADD_FARMER='ADD_FARMER'

export const FARMER_DETAILS_REQUEST='FARMER_DETAILS_REQUEST'
export const FARMER_DETAILS_SUCCESS='FARMER_DETAILS_SUCCESS'
export const FARMER_DETAILS_FAIL='FARMER_DETAILS_FAIL'