export const PESTS_LIST_REQUEST='PESTS_LIST_REQUEST'
export const PESTS_LIST_SUCCESS='PESTS_LIST_SUCCESS'
export const PESTS_LIST_FAIL='PESTS_LIST_FAIL'

export const PESTS_ADD_REQUEST='PESTS_ADD_REQUEST'
export const PESTS_ADD_SUCCESS='PESTS_ADD_SUCCESS'
export const PESTS_ADD_FAIL='PESTS_ADD_FAIL'

