export const PRACTICES_LIST_REQUEST='PRACTICES_LIST_REQUEST'
export const PRACTICES_LIST_SUCCESS='PRACTICES_LIST_SUCCESS'
export const PRACTICES_LIST_FAIL='PRACTICES_LIST_FAIL'

export const PRACTICES_ADD_REQUEST='PRACTICES_ADD_REQUEST'
export const PRACTICES_ADD_SUCCESS='PRACTICES_ADD_SUCCESS'
export const PRACTICES_ADD_FAIL='PRACTICES_ADD_FAIL'